root: true
parser: "@typescript-eslint/parser"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:unicorn/recommended"
  - "prettier"
plugins:
  - "@typescript-eslint"
rules:
  "unicorn/filename-case": 0
  "unicorn/numeric-separators-style": 0
  "unicorn/no-zero-fractions": 0
  "unicorn/prevent-abbreviations": 0
  "unicorn/no-null": 0
  "unicorn/no-useless-undefined": 0
  "@typescript-eslint/consistent-type-imports":
    - "error"
    -   prefer: "type-imports"
        fixStyle: "separate-type-imports"
ignorePatterns:
  - "node_modules"
